Update run_onchange_before_10-install-package.sh.tmpl

diff --git a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
@@ -11,24 +11,8 @@ packages+=({{- . | quote -}})
 aur_packages+=({{- . | quote -}})
 {{- end }}
 
-_install_confirm() {
-  local response
-  echo -n -e "$1"
-  read -r response
+echo -e "\n===>  Installing base packages...\n"
+{{ .chezmoi.config.data.aurHelper }} -S --needed "${packages[@]}" || echo -e "\n${ORANGE}WARNING${NC}: Package installation failed.\n"
 
-  if [[ "$response" =~ ^[Yy]$|^$ ]]; then
-    return 0
-  else
-    return 1
-  fi
-}
-
-if _install_confirm "Install base packages? [Y/n] " -eq 0; then
-  echo -e "\n===>  Installing base packages...\n"
-  {{ .chezmoi.config.data.aurHelper }} -S --needed "${packages[@]}" || echo -e "\n${ORANGE}WARNING${NC}: Package installation failed or cancelled by user.\n"
-fi
-
-if _install_confirm "Install AUR packages? [Y/n] " -eq 0; then
-  echo -e "\n===>  Installing AUR packages...\n"
-  {{ .chezmoi.config.data.aurHelper }} -S --needed "${aur_packages[@]}" || echo -e "\n${ORANGE}WARNING${NC}: Package installation failed or cancelled by user.\n"
-fi
+echo -e "\n===>  Installing AUR packages...\n"
+{{ .chezmoi.config.data.aurHelper }} -S --needed "${aur_packages[@]}" || echo -e "\n${ORANGE}WARNING${NC}: Package installation failed.\n"
