Update dot_zshrc

diff --git a/dot_config/zsh/dot_zshrc b/dot_config/zsh/dot_zshrc
--- a/dot_config/zsh/dot_zshrc
+++ b/dot_config/zsh/dot_zshrc
@@ -8,11 +8,12 @@ if [[ -n ${ZSH_PROMPT} && ${SKIP_PROMPT_LOAD} != 1 ]]; then
   source $ZDOTDIR/prompts/"$ZSH_PROMPT".zsh || echo -e "==>  Failed to source ${ZSH_PROMPT}"
 fi
 
-if [[ -n ${ZSH_PLUGIN_FRAMEWORK} ]]; then
-  source $ZDOTDIR/plugins/"$ZSH_PLUGIN_FRAMEWORK".zsh || echo -e "==>  Failed to source ${ZSH_PLUGIN_FRAMEWORK}"
-fi
-
 # Source other configs in conf.d
 for file in "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/"*.zsh; do
   [ -r "$file" ] && source "$file" || echo -e "==>  Failed to source $file"
 done
+
+# Load plugin manager framework
+if [[ -n ${ZSH_PLUGIN_FRAMEWORK} ]]; then
+  source $ZDOTDIR/plugins/"$ZSH_PLUGIN_FRAMEWORK".zsh || echo -e "==>  Failed to source ${ZSH_PLUGIN_FRAMEWORK}"
+fi
