Update dot_zshrc

diff --git a/dot_config/zsh/dot_zshrc b/dot_config/zsh/dot_zshrc
--- a/dot_config/zsh/dot_zshrc
+++ b/dot_config/zsh/dot_zshrc
@@ -1,18 +1,31 @@
 #!/usr/bin/env zsh
 
-if [[ -f "$ZDOTDIR/settings.zsh" ]]; then
-  source $ZDOTDIR/settings.zsh
-fi
+#if [[ -f "$ZDOTDIR/settings.zsh" ]]; then
+#  source $ZDOTDIR/settings.zsh
+#fi
 
-if [[ -n ${ZSH_PLUGIN_FRAMEWORK} ]]; then
-  source $ZDOTDIR/plugins/"$ZSH_PLUGIN_FRAMEWORK".zsh || echo -e "==>  Failed to source ${ZSH_PLUGIN_FRAMEWORK}"
-fi
+#if [[ -n ${ZSH_PLUGIN_FRAMEWORK} ]]; then
+#  source $ZDOTDIR/plugins/"$ZSH_PLUGIN_FRAMEWORK".zsh || echo -e "==>  Failed to source ${ZSH_PLUGIN_FRAMEWORK}"
+#fi
 
-if [[ -n ${ZSH_PROMPT} && ${SKIP_PROMPT_LOAD} != 1 ]]; then
-  source $ZDOTDIR/prompts/"$ZSH_PROMPT".zsh || echo -e "==>  Failed to source ${ZSH_PROMPT}"
-fi
+#if [[ -n ${ZSH_PROMPT} && ${SKIP_PROMPT_LOAD} != 1 ]]; then
+#  source $ZDOTDIR/prompts/"$ZSH_PROMPT".zsh || echo -e "==>  Failed to source ${ZSH_PROMPT}"
+#fi
 
-# Source other configs in conf.d
-for file in "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/"*.zsh; do
-  [ -r "$file" ] && source "$file" || echo -e "==>  Failed to source $file"
-done
+## Source other configs in conf.d
+#for file in "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/"*.zsh; do
+#  [ -r "$file" ] && source "$file" || echo -e "==>  Failed to source $file"
+#done
+
+
+
+# Source configuration files in order
+source "$ZDOTDIR/env.zsh"
+source "$ZDOTDIR/history.zsh"
+source "$ZDOTDIR/keybindings.zsh"
+source "$ZDOTDIR/completion.zsh"
+source "$ZDOTDIR/plugins.zsh"
+source "$ZDOTDIR/fzf.zsh"
+source "$ZDOTDIR/zoxide.zsh"
+source "$ZDOTDIR/aliases.zsh"
+source "$ZSH_CONFIG_DIR/functions.zsh"
